### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by samuelhorobin** [CubesCocktail/ItemDrink#1]
**Receiving errors when attempting to use the back button**

[12:58:31 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "com.github.zamponimarco.cubescocktail.libs.model.ModelPath.getLast()" is null
[12:58:31 WARN]:        at cubescocktail-0.1.1.jar//com.github.zamponimarco.cubescocktail.libs.gui.model.ModelObjectInventoryHolder.initializeInventory(ModelObjectInventoryHolder.java:53)
[12:58:31 WARN]:        at cubescocktail-0.1.1.jar//com.github.zamponimarco.cubescocktail.libs.gui.PluginInventoryHolder.getInventory(PluginInventoryHolder.java:110)
[12:58:31 WARN]:        at cubescocktail-0.1.1.jar//com.github.zamponimarco.cubescocktail.libs.gui.PluginInventoryHolder.lambda$getBackConsumer$2(PluginInventoryHolder.java:98)
[12:58:31 WARN]:        at cubescocktail-0.1.1.jar//com.github.zamponimarco.cubescocktail.libs.gui.PluginInventoryHolder.handleClickEvent(PluginInventoryHolder.java:47)
[12:58:31 WARN]:        at cubescocktail-0.1.1.jar//com.github.zamponimarco.cubescocktail.libs.listener.PluginInventoryHolderClickListener.onInventoryClick(PluginInventoryHolderClickListener.java:44)
[12:58:31 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor646.execute(Unknown Source)
[12:58:31 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[12:58:31 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[12:58:31 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:58:31 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[12:58:31 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[12:58:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[12:58:31 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3165)
[12:58:31 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[12:58:31 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[12:58:31 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[12:58:31 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[12:58:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[12:58:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[12:58:31 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[12:58:31 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[12:58:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[12:58:31 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[12:58:31 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[12:58:31 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[12:58:31 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[12:58:31 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[12:58:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[12:58:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by samuelhorobin** [comment]
Go to action groups -> go back just fine
Go to action groups -> Add an action group -> Enter nothing and press back -> Press back again -> Error
